### ISSUE TITLE
Bounding Box Feature

### ISSUE THREAD

**Issue by Noki** [flopp/go-staticmaps#18]
Hi! 

I just had a look at your static maps implementation. I really like it but I think it should be possible to set/limit the map using a bounding box in addition to all the other wonderful ways you implemented.

My usecase for this would be to show a whole country on the map and than highlight a city or an area within the country.

Any plans to implement this?

Best regards
Tobias

**Comment by flopp** [comment]
Great idea! I think I can easily implement the following:

Golang interface:
```
func (m *Context) SetBoundingBox(corner1 s2.LatLng, corner2 s2.LatLng)
```
or 
```
func (m *Context) SetBoundingBox(bbox s2.Rect)
```

Command line interface:
```
--bbox LATLNG|LATLNG
```
where the two LATLNGs are opposite corners of the bbox.

**Comment by tonglil** [comment]
I'm having some problems using the bounding box feature.
It doesn't seem to scale the map to the bounding box when using `--zoom` or `--width/--height`.

For example, I would like a 5000 x 5000 px image, bound by `LATLNG|LATLNG`. However if I change the image to 8000 x 8000 px with the same `LATLNG|LATLNG`, then it will produce a different image.

It also doesn't seem to actually bound to the `LATLNG` specified, but slightly outside of it.

**Comment by tonglil** [comment]
For example:

`49.351324,-123.247843|49.189628,-122.999621`

## Expected bounds (at markers)

NW: https://www.openstreetmap.org/?mlat=49.351324&mlon=-123.247843#map=14/49.351324/-123.247843
<img width="960" alt="image" src="https://user-images.githubusercontent.com/3250776/57952862-4d190b00-78a3-11e9-969d-aba934379cc6.png">

SE: https://www.openstreetmap.org/?mlat=49.189628&mlon=-122.999621#map=14/49.189628/-122.999621
<img width="960" alt="image" src="https://user-images.githubusercontent.com/3250776/57952912-6de16080-78a3-11e9-9be4-531f24167e9f.png">

## Generated maps with different zooms using bbox

The bounding box is not "bound" on the actual coordinates.

CLI zoom 10: `create-static-map --bbox="49.351324,-123.247843|49.189628,-122.999621" --zoom="10"`
![map](https://user-images.githubusercontent.com/3250776/57952530-5f467980-78a2-11e9-82a1-d7125a2f1712.png)

CLI zoom 14: `create-static-map --bbox="49.351324,-123.247843|49.189628,-122.999621" --zoom="14"`
![map](https://user-images.githubusercontent.com/3250776/57952485-3e7e2400-78a2-11e9-90e6-39493ac52a9b.png)

CLI zoom 15: `create-static-map --bbox="49.351324,-123.247843|49.189628,-122.999621" --zoom="15"`
![map](https://user-images.githubusercontent.com/3250776/57952499-48078c00-78a2-11e9-876e-c2c812f39252.png)

## Generated maps with different sizes using bbox

Notice the different edges. I think the maximum is 5000px before it expands beyond the bbox?

CLI height 1000: `create-static-map --bbox="49.351324,-123.247843|49.189628,-122.999621" --height="1000" --width="1000"`
![map](https://user-images.githubusercontent.com/3250776/57952966-949f9700-78a3-11e9-82c9-3dc2fedef744.png)

CLI height 5000: `create-static-map --bbox="49.351324,-123.247843|49.189628,-122.999621" --height="5000" --width="5000"` (converted to jpg to upload)
![out](https://user-images.githubusercontent.com/3250776/57953465-f90f2600-78a4-11e9-8ceb-6be6bde5eba7.jpg)
