### ISSUE TITLE
Network error when downloading tile produces map with missing tile

### ISSUE THREAD

**Issue by pushinginertia** [flopp/go-staticmaps#34]
If the fetch of a tile fails due to a network error, the `Context.renderLayer` function ignores the error and renders the map with a beige square where the tile would have been placed.

This function currently logs that the tile couldn't be downloaded, but this doesn't work for unattended jobs that generate static maps and the map has to be generated correctly.

Suggest adding a `return err` as described in this code fragment. The caller can then make the choice to retry if it's due to a transient network error.

```go
func (m *Context) renderLayer(gc *gg.Context, zoom int, trans *transformer, tileSize int, provider *TileProvider) error {
...
	if tileImg, err := t.Fetch(zoom, x, y); err == nil {
		gc.DrawImage(tileImg, xx*tileSize, yy*tileSize)
	} else {
		log.Printf("Error downloading tile file: %s", err)
		return err
	}
```

**Comment by flopp** [comment]
I just merged the corresponding PR (#35)...

**Comment by pushinginertia** [comment]
Thank you!

**Comment by amatiasq** [comment]
This is happening again.
The return err is gone: https://github.com/flopp/go-staticmaps/blob/master/context.go#L675-L678
Actually the only difference between the block of code that ignores the error and the one that doesn't is that the first one prints (ignored) to the log.

We're getting a map with a missing tile exactly half of the times we render it.

<img width="600" height="350" alt="Image" src="https://github.com/user-attachments/assets/5ddccb17-8af1-4565-91cb-81d7957c4331" />
<img width="600" height="350" alt="Image" src="https://github.com/user-attachments/assets/42c7df83-c85d-43c4-abbd-4d6be0a9d994" />

There is a `Error downloading tile file: error 404: tile not found` printed to stderr but other than that we have no automatic way of detecting something was wrong with the render.
