### ISSUE TITLE
Allow configurable tile cache directory location and file mode

### ISSUE THREAD

**Issue by pushinginertia** [flopp/go-staticmaps#37]
It's currently not possible to set the cache directory when instantiating a staticmaps context to point at a user-specified path, because it defaults to a directory under the executing user's home directory via the `appdirs` library.

There are use cases where we might want to store the tile cache in a static directory defined by the user of the library:
* A multinode service might save to a cache on an NFS mount.
* Running this within a docker container would require using a directory mounted into the container if the cache should persist across docker instances.
* Since tiles are continuously updated on the mapping service, we might want to write a job that periodically removes cached tiles older than a certain age and it might be preferable to configure this directory outside the library.

The directory permissions are also created as 777, which allows any user on the host to write to anywhere within the cache. It would also be helpful to specify the file mask as an argument when instantiating the cache for the user of the library to determine.

Suggest addition of a `TileCache` interface that provides the path and permissions to `TileFetcher`. This could be instantiated by default with the current behaviour but would allow 

```go
type TileCache interface {
    // Root path to store cached tiles in with no trailing slash.
    Path() string
    // Permission to set when creating missing cache directories.
    Perm() os.FileMode
}
```

**Comment by flopp** [comment]
That sounds reasonable!

**Comment by flopp** [comment]
Merged...
