### ISSUE TITLE
Changing TileProvider, but old tiles still cached

### ISSUE THREAD

**Issue by quite** [flopp/go-staticmaps#38]
I was confused by changing TileProvider didn't have any effect. And realized it was cached, @Luzifer has a fix for that in their fork at https://github.com/Luzifer/go-staticmaps -- it uses a separate cache for each provider.

There are also an update to use modules, and as well being lenient with non-existing (404) overlay-tiles. They both feel sound.

Would you like to submit a PR @Luzifer / bring these in @flopp  ? :)

**Comment by flopp** [comment]
Sure, I'd be happy to merge such a PR!

**Comment by Luzifer** [comment]
I've created two PRs for the features mentioned above. For the Go modules support @flopp should run `go mod init` and add those two files themselves as it makes no sense to add my commit as a PR (would contain my module path).

**Comment by flopp** [comment]
Ok, I've merged the two PRs and created `go.mod` & `go.sum` (I hope I've done everything right).
Thank you for your support and helpful suggestions!
