### ISSUE TITLE
Custom marker size,  cannot parse size string: 30

### ISSUE THREAD

**Issue by kani** [flopp/go-staticmaps#47]
Thank you for this great project!

I tried to use custom marker size it says 'cannot parse size', not sure what I'm doing wrong here. Here is my command...

`create-static-map --width 800 --height 300 --marker "size:'30'|label:1|labelcolor:white|color:blue|8.89698,77.36292666666667"  ...... `

**Comment by flopp** [comment]
Could you try again without single quotes, e.g. `--marker "size:30|...`?

**Comment by kani** [comment]
no luck, still throwing the same error message: `2020/11/23 09:40:33 cannot parse size string: 30
`

**Comment by kani** [comment]
@flopp thanks for fixing this quickly. How do I update the command line version?

**Comment by flopp** [comment]
I guess it's just a simple `go get -u github.com/flopp/go-staticmaps/create-static-map`

**Comment by kani** [comment]
That worked, thanks again!
