### ISSUE TITLE
MapObject margins

### ISSUE THREAD

**Issue by aivchen** [flopp/go-staticmaps#50]
Another interesting case since you added an ability to add custom objects to the map: sometimes map object can be not symmetrical. 
For example I want to add a custom marker like this:

![image](https://user-images.githubusercontent.com/4580308/105782328-5cf85600-5f85-11eb-82f1-b022c775e687.png)

And of course if the marker is placed on the left edge of the map it will be cropped. Also in my case `determineCenter` method works incorrectly as it doesn't take into account text block.

Right now we have a method `ExtraMarginPixels` in `MapObject` interface. As I understand it just adds the same margin to top/bottom and right/left margin to the entire output picture. But would be good to have more smart function.

And again, thank you a lot for this project!

**Comment by flopp** [comment]
Yes, that's right. `ExtraMarginPixels` is for top/bottom/left/right margins.
I guess a 4-valued `PixelBounds() (float64, float64, float64, float64)` function returning separate top/bottom/left/right margins would suffice for your use case?

**Comment by aivchen** [comment]
I assume yes. I investigated your code and I assume it's not easy to implement. Especially in determineCenter method.
Method `determineCenter(bounds s2.Rect)` receives a variable which describes geographic boundaries, but `PixelMargins` will return margins in pixels. I assume we should make new s2.LatLng points using values from `PixelMargins` and add them to the s2.Rect bounds but I have no idea how to do it:)

**Comment by flopp** [comment]
Ok, `MapObject.ExtraMarginPixels` now returns the left, top, right, bottom pixel extent.

Do you want to replace the dynamic maps in https://www.airportia.com/ by static, pre-rendered maps?

**Comment by aivchen** [comment]
Thanks, but seems it doesn't work as expected.
Have a look at my example:

```go
package main

import (
	"github.com/flopp/go-staticmaps"
	"github.com/fogleman/gg"
	"github.com/golang/geo/s2"
)

type Circle struct {
	sm.MapObject
	Position   s2.LatLng
	leftMargin float64
}

// leftMargin - a place where we draw a vertical line
func NewCircle(pos s2.LatLng, leftMargin float64) *Circle {
	s := new(Circle)
	s.Position = pos
	s.leftMargin = leftMargin
	return s
}

func (s *Circle) ExtraMarginPixels() (float64, float64, float64, float64) {
	return 0, 0, 0, s.leftMargin
}

func (s *Circle) Bounds() s2.Rect {
	r := s2.EmptyRect()
	r = r.AddPoint(s.Position)
	return r
}

func (s *Circle) Draw(gc *gg.Context, trans *sm.Transformer) {
	if !sm.CanDisplay(s.Position) {
		return
	}

	x, y := trans.LatLngToXY(s.Position)
	gc.ClearPath()
	gc.SetLineWidth(1)

	gc.DrawCircle(x, y, 5)
	gc.SetHexColor("#ff0000")
	gc.Fill()

	gc.SetLineWidth(1)
	gc.SetHexColor("#ff0000")
	gc.DrawLine(x-s.leftMargin, y-20, x-s.leftMargin, y+20)
	gc.Stroke()
}

func main() {
	ctx := sm.NewContext()
	ctx.SetSize(700, 500)
	ctx.AddObject(NewCircle(s2.LatLngFromDegrees(52.51450, 13.35012), 0)) //Center Marker
	ctx.AddObject(NewCircle(s2.LatLngFromDegrees(52.51450, 13.25012), 50)) //Left Marker - try to change it to 100.
	ctx.AddObject(NewCircle(s2.LatLngFromDegrees(52.51450, 13.45012), 0)) //Right Marker

	img, err := ctx.Render()
	if err != nil {
		panic(err)
	}

	if err := gg.SavePNG("out.png", img); err != nil {
		panic(err)
	}
}

```

Try to change the left margin of the left market to 100px. In this case, the vertical line is cropped. I would expect a zoom level change.

> Do you want to replace the dynamic maps in https://www.airportia.com/ by static, pre-rendered maps?

Yup. Pre-rendering and a bit of redesign:)

**Comment by flopp** [comment]
Ah, I think you're using a wrong margin order. It should be `left, top, right, bottom`, so in your case: `return s.leftMargin, 0, 0, 0`

**Comment by aivchen** [comment]
Oh, you are right, sorry (I just used the same order as in CSS):)

Thank you for this improvement!
