### ISSUE TITLE
Link to PkgGoDev in README.md

### ISSUE THREAD

**Issue by esperlu** [flopp/go-staticmaps#52]
Hi,

The link to PkgGoDev in README.md points to a blank page. The correct link should be ``https://pkg.go.dev/github.com/flopp/go-staticmaps``

Very neat and handy piece of code. Thanks.

Jean-Luc

**Comment by flopp** [comment]
Hm. That's exactly where the link points to...

**Comment by esperlu** [comment]
Not exactly. The current link points to `https://pkg.go.dev/badge/github.com/flopp/go-staticmaps` ISO `https://pkg.go.dev/github.com/flopp/go-staticmaps`

Cheers.

Jean-Luc

**Comment by flopp** [comment]
From `README.md`:

    [![PkgGoDev](https://pkg.go.dev/badge/github.com/flopp/go-staticmaps)](https://pkg.go.dev/github.com/flopp/go-staticmaps)

=> the link goes to `https://pkg.go.dev/github.com/flopp/go-staticmaps`
=> the badge is loaded from `https://pkg.go.dev/badge/github.com/flopp/go-staticmaps`

Seems correct to me.

**Comment by esperlu** [comment]
When I open the current raw [REAME.md](https://raw.githubusercontent.com/flopp/go-staticmaps/master/README.md) it shows `See [PkgGoDev](https://pkg.go.dev/badge/github.com/flopp/go-staticmaps) for a complete documentation and...` at line 73

Or maybe it's me ;-)

Not a big deal anyway.

JL

**Comment by flopp** [comment]
@esperlu Uhhh, I just realized that there a two links to PkgGoDev in README.md - one in the header (the "reference" badge image), and one further down in the text. You're absolutely right that the second link is bad! I'll fix it immediately.

Thank you for being persistent and patient with me!
