### ISSUE TITLE
Duplicate Entries GetTileProviders()

### ISSUE THREAD

**Issue by billglover** [flopp/go-staticmaps#56]
The following lines:

https://github.com/flopp/go-staticmaps/blob/2e6e19a99c28a6e68b24e2f2fbcc084da8aee8ac/tile_provider.go#L151-L152

are a duplicate of:

https://github.com/flopp/go-staticmaps/blob/2e6e19a99c28a6e68b24e2f2fbcc084da8aee8ac/tile_provider.go#L159-L160

I suspect these lines can be removed without issue.

**Comment by billglover** [comment]
I'd be happy to create a PR to remove these if it would be useful.

**Comment by flopp** [comment]
Oh, you're right. These are obvious duplicates (maybe from a merge conflict...).
If you want to provide a PR, please go ahead!
