### ISSUE TITLE
Labels in thunderforest-transport look weird

### ISSUE THREAD

**Issue by flopp** [flopp/go-staticmaps#8]
`create-static-map -t thunderforest-transport -c "52.52,13.38" -z 13`

![map](https://cloud.githubusercontent.com/assets/272596/13013483/f540fcaa-d1af-11e5-9328-caeef7b8a97a.png)

E.g. north east quadrant has some cut off/partial labels, although the map itself (roads, rivers, etc.) look perfect :(

**Comment by crizzs** [comment]
For some maps, this is unavoidable. Might due to labels overlapping and size of the words at particular zoom level.

**Comment by Noki** [comment]
This is an issues of the tile provider, not a issue created by go-staticmaps. I think this can be closed. You can contact the tile provider to fix the rendering of the tiles.

**Comment by flopp** [comment]
You're absolutely right...
